import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, describe, expect, it, vi } from 'vitest';

import {
  BOARDS,
  archivePath,
  buildArchive,
  deleteArchivedComments,
  deleteMonths,
  deleteVerdict,
  maskLeaks,
  monthWindow,
  normalizeBody,
  parseArchive,
  planArchive,
  renderArchive,
  scanEmailLeaks,
  type ArchivedEntry,
  type LiveComment,
} from './boardArchive';
import { type GitHubClient } from './discordActions';

const ROOT = path.resolve(__dirname, '../..');
const read = (p: string) => fs.readFileSync(path.join(ROOT, p), 'utf-8');
const SCAN_SCRIPT = path.join(ROOT, '.githooks/scan-emails.sh');
const noLeaks = () => [];

// Fixtur-adressene i denne fila MÅ stå på repoets allowlist: pre-commit-vakta
// (#1929) nekter alt annet, og repoet er offentlig. For å se skanneren slå til
// kjøres den derfor også mot en snevrere allowlist i en temp-rot, der
// example.com ikke er tillatt. Skanneren og regelen er de samme.
const LEAK = 'ola@example.com';
const STRICT_ROOT = fs.mkdtempSync(path.join(os.tmpdir(), 'tavle-arkiv-'));
fs.mkdirSync(path.join(STRICT_ROOT, '.githooks'));
fs.writeFileSync(path.join(STRICT_ROOT, '.githooks/email-allowlist.txt'), '^noreply@\n');
afterAll(() => fs.rmSync(STRICT_ROOT, { recursive: true, force: true }));
const scanRepo = (text: string) => scanEmailLeaks(text, { script: SCAN_SCRIPT, root: ROOT });
const scan = (text: string) => scanEmailLeaks(text, { script: SCAN_SCRIPT, root: STRICT_ROOT });

const [LOOP_DRIFT, UTROPEREN] = BOARDS;

function live(entry: ArchivedEntry, id: number, body = entry.body): LiveComment {
  return { ...entry, body, id, htmlUrl: `https://github.com/x/y/issues/1110#issuecomment-${id}` };
}

// ── Arkivformatet: de fire håndlagde filene på main er fasiten ───────────────

describe('parseArchive mot de ekte arkivfilene', () => {
  // Tallene er filenes egne «N kommentarer». En løs `^## `-parser gir 97 i
  // juli-1110, fordi en forge-kontrakt i en kommentar har egne ##-overskrifter.
  it.each([
    ['2026-07-loop-drift-1110.md', 89],
    ['2026-07-utroperen-1208.md', 8],
    ['2026-08-loop-drift-1110.md', 82],
    ['2026-08-utroperen-1208.md', 11],
  ])('%s gir %i oppføringer', (file, count) => {
    expect(parseArchive(read(`docs/loops/logg/${file}`))).toHaveLength(count);
  });

  it('tåler bot-logins med klammer', () => {
    const logins = new Set(
      parseArchive(read('docs/loops/logg/2026-08-loop-drift-1110.md')).map((e) => e.login),
    );
    expect(logins).toContain('claude[bot]');
    expect(logins).toContain('github-actions[bot]');
  });

  it('renderArchive gjenskaper august-fila for #1208 byte for byte', () => {
    const file = read('docs/loops/logg/2026-08-utroperen-1208.md');
    expect(
      renderArchive({ board: UTROPEREN, month: '2026-08', entries: parseArchive(file), masked: [] }),
    ).toBe(file);
  });

  // Headerne i de tre andre har håndskrevne tillegg (etterfylling, maskering),
  // men oppføringsdelen skal være identisk.
  it.each([
    [LOOP_DRIFT, '2026-07', '2026-07-loop-drift-1110.md'],
    [UTROPEREN, '2026-07', '2026-07-utroperen-1208.md'],
    [LOOP_DRIFT, '2026-08', '2026-08-loop-drift-1110.md'],
  ])('oppføringsdelen av %s %s rendres identisk', (board, month, file) => {
    const md = read(`docs/loops/logg/${file}`);
    const rendered = renderArchive({ board, month, entries: parseArchive(md), masked: [] });
    const entriesPart = (s: string) => s.slice(s.indexOf('\n---\n\n## '));
    expect(entriesPart(rendered)).toBe(entriesPart(md));
  });
});

describe('renderArchive ↔ parseArchive', () => {
  it('round-tripper bodyer med ---, ## Problem, json-blokk og tom body', () => {
    const entries: ArchivedEntry[] = [
      { login: 'jdlarssen', createdAt: '2026-09-01T02:17:29Z', body: 'Brief\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_' },
      { login: 'claude[bot]', createdAt: '2026-09-02T10:00:00Z', body: '## Problem\n\nTekst\n\n## Design\n\n```json\n{"a": 1}\n```' },
      { login: 'github-actions[bot]', createdAt: '2026-09-03T11:00:00Z', body: '' },
      { login: 'jdlarssen', createdAt: '2026-09-04T12:00:00Z', body: '---\n\n---' },
    ];
    const md = renderArchive({ board: LOOP_DRIFT, month: '2026-09', entries, masked: [] });
    expect(parseArchive(md)).toEqual(entries);
  });

  it('skriver maskerings-avviket i headeren, og bare når noe ble maskert', () => {
    const entries: ArchivedEntry[] = [{ login: 'a', createdAt: '2026-09-01T00:00:00Z', body: 'x' }];
    const plain = renderArchive({ board: UTROPEREN, month: '2026-09', entries, masked: [] });
    const masked = renderArchive({
      board: UTROPEREN,
      month: '2026-09',
      entries,
      masked: ['noen [at] ukjent.example-x.com'],
    });
    expect(plain).not.toContain('Eneste avvik');
    expect(masked).toContain('Eneste avvik fra verbatim');
    expect(masked).toContain('«noen [at] ukjent.example-x.com»');
    expect(masked).not.toContain('@');
  });

  it('sier «1 kommentar» i entall', () => {
    const md = renderArchive({
      board: UTROPEREN,
      month: '2026-09',
      entries: [{ login: 'a', createdAt: '2026-09-05T00:00:00Z', body: 'x' }],
      masked: [],
    });
    expect(md).toContain('urørt. 1 kommentar,\nperiode 2026-09-05 – 2026-09-05.');
  });
});

describe('monthWindow / archivePath', () => {
  it.each([
    ['2026-09', '2026-09-01T00:00:00Z', '2026-10-01T00:00:00Z', '2026-09-30', 'september 2026'],
    ['2026-12', '2026-12-01T00:00:00Z', '2027-01-01T00:00:00Z', '2026-12-31', 'desember 2026'],
    ['2028-02', '2028-02-01T00:00:00Z', '2028-03-01T00:00:00Z', '2028-02-29', 'februar 2028'],
  ])('%s', (month, startIso, endIso, lastDay, label) => {
    expect(monthWindow(month)).toEqual({ startIso, endIso, lastDay, label });
  });

  it('avviser ugyldig måned', () => {
    expect(() => monthWindow('2026-13')).toThrow();
    expect(() => monthWindow('26-09')).toThrow();
  });

  it('følger det etablerte filnavnet', () => {
    expect(archivePath(LOOP_DRIFT, '2026-09')).toBe('docs/loops/logg/2026-09-loop-drift-1110.md');
    expect(archivePath(UTROPEREN, '2026-09', 'tmp/logg')).toBe('tmp/logg/2026-09-utroperen-1208.md');
  });
});

// ── Normalisering + maskering: én pipeline for begge faser ───────────────────

describe('normalizeBody', () => {
  it('gjør CRLF til LF, fjerner trailing whitespace og blanke kant-linjer', () => {
    expect(normalizeBody('\r\nlinje 1  \r\n\tinnrykk\t\r\n\r\n')).toBe('linje 1\n\tinnrykk');
  });
});

describe('e-postmaskering (#1929)', () => {
  it('scan-emails.sh finner en adresse utenfor allowlista, og respekterer den', () => {
    expect(scan(`Skriv til ${LEAK} i dag\n`)).toEqual([LEAK]);
    expect(scan('noreply@example.com\n')).toEqual([]);
    expect(scanRepo(`${LEAK}\n`)).toEqual([]);
  });

  it('maskLeaks gjør adressen om til «[at]»-formen', () => {
    expect(maskLeaks(`skrivefeil: ${LEAK}`, [LEAK])).toEqual({
      text: 'skrivefeil: ola [at] example.com',
      masked: ['ola [at] example.com'],
    });
  });

  // Arkivfila har bare den maskerte formen. Slette-porten må derfor kjøre samme
  // pipeline på den ferske body-en — ellers blir hver maskert kommentar et evig
  // avvik som aldri slettes.
  it.each([
    ['LF', `Hei\nskrivefeil: ${LEAK}\n`],
    ['CRLF', `Hei\r\nskrivefeil: ${LEAK}\r\n`],
  ])('maskert kommentar gir match mot sin rå live-body (%s)', (_label, raw) => {
    const comment: LiveComment = {
      id: 1,
      login: 'jdlarssen',
      createdAt: '2026-09-02T08:00:00Z',
      body: raw,
      htmlUrl: 'u',
    };
    const built = buildArchive({ board: LOOP_DRIFT, month: '2026-09', comments: [comment], scan });
    expect(built?.markdown).toContain('ola [at] example.com');
    expect(built?.markdown).not.toContain(LEAK);
    const [archived] = parseArchive(built!.markdown);
    expect(deleteVerdict(archived, { body: raw }, scan)).toBe('match');
  });

  it('buildArchive nekter å returnere en fil som fortsatt ikke er ren', () => {
    const stubborn = () => [LEAK];
    const comment: LiveComment = { id: 1, login: 'a', createdAt: '2026-09-02T08:00:00Z', body: 'x', htmlUrl: 'u' };
    expect(() => buildArchive({ board: LOOP_DRIFT, month: '2026-09', comments: [comment], scan: stubborn })).toThrow(
      /ikke ren/,
    );
  });
});

describe('buildArchive', () => {
  const c = (id: number, createdAt: string): LiveComment => ({
    id,
    login: 'jdlarssen',
    createdAt,
    body: `kommentar ${id}`,
    htmlUrl: 'u',
  });

  it('tar kun månedens kommentarer, sortert på tid', () => {
    const built = buildArchive({
      board: LOOP_DRIFT,
      month: '2026-09',
      comments: [c(3, '2026-09-30T23:59:59Z'), c(1, '2026-08-31T23:59:59Z'), c(2, '2026-09-01T00:00:00Z'), c(4, '2026-10-01T00:00:00Z')],
      scan: noLeaks,
    });
    expect(built?.entries.map((e) => e.body)).toEqual(['kommentar 2', 'kommentar 3']);
  });

  // En body med en linje på overskriftsformen ville gitt en fil som ikke leses
  // tilbake likt — da skal ingenting skrives, i stedet for en fil slette-fasen
  // senere kvelner på.
  it('nekter å skrive en fil som ikke parses tilbake til de samme oppføringene', () => {
    const tricky = { ...c(1, '2026-09-02T00:00:00Z'), body: 'sitat:\n\n## jdlarssen · 2026-08-01T00:00:00Z\n\nhei' };
    expect(() => buildArchive({ board: LOOP_DRIFT, month: '2026-09', comments: [tricky], scan: noLeaks })).toThrow(
      /leses ikke tilbake/,
    );
  });

  it('gir null når måneden er tom', () => {
    expect(buildArchive({ board: LOOP_DRIFT, month: '2026-09', comments: [], scan: noLeaks })).toBeNull();
  });
});

// ── Planlegging: hvilke måneder arkiveres ─────────────────────────────────────

describe('planArchive', () => {
  const now = new Date('2026-10-01T04:10:00Z');
  const comment = (createdAt: string): LiveComment => ({ id: 1, login: 'a', createdAt, body: 'x', htmlUrl: 'u' });
  const comments = {
    1110: [comment('2026-09-05T00:00:00Z'), comment('2026-10-01T02:00:00Z')],
    1208: [comment('2026-09-06T00:00:00Z')],
  };

  it('uten --month: kun måneder før inneværende, begge tavler', () => {
    const plan = planArchive({ comments, now, dryRun: false, exists: () => false });
    expect(plan.work.map((w) => `${w.month} #${w.board.issue}`)).toEqual(['2026-09 #1110', '2026-09 #1208']);
  });

  it('måned som alt har arkivfil er en no-op med tydelig logglinje', () => {
    const plan = planArchive({ comments, now, month: '2026-09', dryRun: false, exists: () => true });
    expect(plan.work).toEqual([]);
    expect(plan.log).toEqual([
      '2026-09 #1110: fil finnes — hopper over.',
      '2026-09 #1208: fil finnes — hopper over.',
    ]);
  });

  it('tom tavle gir logglinje, den andre arkiveres', () => {
    const plan = planArchive({ comments: { 1110: comments[1110], 1208: [] }, now, dryRun: false, exists: () => false });
    expect(plan.work.map((w) => w.board.issue)).toEqual([1110]);
    expect(plan.log).toContain('2026-09 #1208: ingen kommentarer — ingen fil.');
  });

  it('ekte modus nekter inneværende måned; dry-run tillater den', () => {
    expect(() => planArchive({ comments, now, month: '2026-10', dryRun: false, exists: () => false })).toThrow(
      /inneværende/,
    );
    const plan = planArchive({ comments, now, month: '2026-10', dryRun: true, exists: () => false });
    expect(plan.work.map((w) => w.board.issue)).toEqual([1110]);
  });

  it('ingen gamle kommentarer gir én logglinje og ingen arbeid', () => {
    const plan = planArchive({ comments: { 1110: [], 1208: [] }, now, dryRun: false, exists: () => false });
    expect(plan.work).toEqual([]);
    expect(plan.log).toEqual(['ingen kommentarer før 2026-10 — ingenting å arkivere.']);
  });
});

describe('deleteMonths', () => {
  const now = new Date('2026-09-02T04:10:00Z');
  const files = ['README.md', '2026-07-loop-drift-1110.md', '2026-09-utroperen-1208.md', '2026-08-utroperen-1208.md', '2026-06-utroperen-1208.md', '2026-08-loop-drift-1110.md'];
  it('tar de to nyeste månedene før inneværende som standard', () => {
    expect(deleteMonths(files, now)).toEqual(['2026-08', '2026-07']);
  });
  it('--month avgrenser til nøyaktig den måneden', () => {
    expect(deleteMonths(files, now, '2026-06')).toEqual(['2026-06']);
  });
  it('nekter inneværende måned', () => {
    expect(() => deleteMonths(files, now, '2026-09')).toThrow(/inneværende/);
  });
});

// ── Slette-porten: null-test (ingen DELETE uten byte-identisk kopi) ──────────

type Call = { method: string; path: string };
function recordingGh(deleteStatus = 204) {
  const calls: Call[] = [];
  const gh: GitHubClient = {
    rest: vi.fn(async (method, p) => {
      calls.push({ method, path: p });
      return { status: method === 'DELETE' ? deleteStatus : 200, json: null };
    }),
    graphql: vi.fn(async () => ({ status: 500, json: null })),
  };
  return { gh, deletes: () => calls.filter((c) => c.method === 'DELETE') };
}

describe('deleteArchivedComments', () => {
  const REPO = 'jdlarssen/golf-app';
  const archived: ArchivedEntry = { login: 'jdlarssen', createdAt: '2026-09-02T08:00:00Z', body: 'Morgenbrief\n\nalt vel' };
  const NOW = new Date('2026-10-02T04:10:00Z');

  it.each([
    ['mismatch (ett tegn avvik) → ingen DELETE', live(archived, 11, 'Morgenbrief\n\nalt vel!'), false, 0],
    ['mismatch i dry-run → ingen DELETE', live(archived, 11, 'Morgenbrief\n\nalt vel!'), true, 0],
    ['match i dry-run → ingen DELETE', live(archived, 11), true, 0],
    ['match → nøyaktig én DELETE', live(archived, 11), false, 1],
  ])('%s', async (_label, liveComment, dryRun, expectedDeletes) => {
    const { gh, deletes } = recordingGh();
    await deleteArchivedComments({ gh, repo: REPO, archived: [archived], live: [liveComment], dryRun, scan: noLeaks, now: NOW });
    expect(deletes()).toHaveLength(expectedDeletes);
    if (expectedDeletes === 1) expect(deletes()[0].path).toBe(`/repos/${REPO}/issues/comments/11`);
  });

  it('returnerer avviket i stedet for å kaste', async () => {
    const { gh } = recordingGh();
    const liveComment = live(archived, 11, 'redigert');
    const result = await deleteArchivedComments({ gh, repo: REPO, archived: [archived], live: [liveComment], dryRun: false, scan: noLeaks, now: NOW });
    expect(result.mismatches).toEqual([{ login: 'jdlarssen', createdAt: archived.createdAt, htmlUrl: liveComment.htmlUrl }]);
    expect(result.deleted).toBe(0);
  });

  it('kommentar som alt er borte telles som missing, uten kall', async () => {
    const { gh, deletes } = recordingGh();
    const result = await deleteArchivedComments({ gh, repo: REPO, archived: [archived], live: [], dryRun: false, scan: noLeaks, now: NOW });
    expect(result).toMatchObject({ missing: 1, deleted: 0, mismatches: [], failures: [] });
    expect(deletes()).toHaveLength(0);
  });

  it('DELETE som ikke svarer 204 er en feil, ikke en sletting', async () => {
    const { gh } = recordingGh(403);
    const result = await deleteArchivedComments({ gh, repo: REPO, archived: [archived], live: [live(archived, 11)], dryRun: false, scan: noLeaks, now: NOW });
    expect(result.deleted).toBe(0);
    expect(result.failures).toEqual(['jdlarssen · 2026-09-02T08:00:00Z: DELETE svarte HTTP 403']);
  });

  it('dupliserte nøkler stopper hele tavla før noe slettes', async () => {
    const { gh, deletes } = recordingGh();
    const result = await deleteArchivedComments({
      gh,
      repo: REPO,
      archived: [archived],
      live: [live(archived, 11), live(archived, 12)],
      dryRun: false,
      scan: noLeaks,
      now: NOW,
    });
    expect(deletes()).toHaveLength(0);
    expect(result.duplicates).toEqual(['jdlarssen · 2026-09-02T08:00:00Z']);
  });

  // Inneværende måned røres aldri, heller ikke med en byte-lik kopi (f.eks. en
  // fil som kom på feil ref).
  it('kommentar fra inneværende måned slettes ikke, og meldes', async () => {
    const { gh, deletes } = recordingGh();
    const result = await deleteArchivedComments({
      gh,
      repo: REPO,
      archived: [archived],
      live: [live(archived, 11)],
      dryRun: false,
      scan: noLeaks,
      now: new Date('2026-09-15T12:00:00Z'),
    });
    expect(deletes()).toHaveLength(0);
    expect(result.failures).toEqual(['jdlarssen · 2026-09-02T08:00:00Z: inneværende måned — røres ikke']);
  });
});

// ── Lockstep mot workflow + bash-lim ──────────────────────────────────────────

describe('lockstep mot .github/workflows/tavle-arkiv.yml', () => {
  const workflow = read('.github/workflows/tavle-arkiv.yml');
  const glue = read('.github/scripts/tavle-arkiv.sh');

  it.each([
    'contents: write',
    'issues: write',
    'pull-requests: write',
    'group: tavle-arkiv',
    "cron: '10 4 1-3 * *'",
    'bash .github/scripts/tavle-arkiv.sh',
  ])('workflowen inneholder %s', (needle) => {
    expect(workflow).toContain(needle);
  });

  // workflow_dispatch sjekker ut valgfri gren; «kopien ligger på main» må
  // håndheves, ikke antas.
  it('bash-limet nekter ekte kjøring utenfor main', () => {
    expect(glue).toContain('git rev-parse origin/main');
  });

  it('bash-limet kjører runneren og åpner PR-en via robot-pr.sh (#1701)', () => {
    expect(glue).toContain('scripts/loops/archive-boards.ts');
    expect(glue).toContain('source .github/scripts/robot-pr.sh');
    expect(glue).toContain('robot_pr_verify_not_parked');
  });
});
