import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import {
  buildSweepComment,
  classifyNattDraft,
  DELIVERY_MARKER,
  lastNattMarker,
  MIN_QUIET_MINUTES,
  NATT_BRANCH_PREFIX,
  NATT_REVIEW_LABEL,
  preCommentSkipReason,
  REBUILD_MARKER,
  SWEEP_MARKER,
  type NattDraftPr,
} from './draftSweep';

// Klokka i testene: PR-er «eldre enn» NOW minus 90 min er stille nok til å flippes.
const NOW = new Date('2026-08-29T06:00:00Z');
const STILLE = '2026-08-29T03:00:00Z'; // 3 t siden
const FERSK = '2026-08-29T05:30:00Z'; // 30 min siden

const base: NattDraftPr = {
  isOpen: true,
  isDraft: true,
  headRef: 'claude/natt-1769-draft-flipp',
  labels: [NATT_REVIEW_LABEL],
  updatedAt: STILLE,
  commentBodies: ['🤖 Leveranse: bygget #1769 — gates grønne, kryss-modell-gate CONFIRM.'],
};

const pr = (over: Partial<NattDraftPr> = {}): NattDraftPr => ({ ...base, ...over });

describe('classifyNattDraft', () => {
  it('flipper en ferdig bokført, stille natt-draft', () => {
    expect(classifyNattDraft(pr(), NOW)).toEqual({ action: 'flip' });
  });

  // Regel 1 — ikke en åpen draft.
  it.each([
    ['lukket PR', { isOpen: false }],
    ['allerede ready (ikke draft)', { isDraft: false }],
    ['lukket OG ready', { isOpen: false, isDraft: false }],
  ])('%s → skip ikke-åpen-draft', (_navn, over) => {
    expect(classifyNattDraft(pr(over), NOW)).toEqual({
      action: 'skip',
      reason: 'ikke-åpen-draft',
    });
  });

  // Regel 2 — natt-signaturen (branch-prefiks + label). Interaktive økters drafts
  // bærer ingen av delene og skal ALDRI røres (#1516).
  it.each([
    ['interaktiv økts branch', { headRef: 'claude/mange-issues-a70214' }],
    ['helt annen branch', { headRef: 'fiks-noe' }],
    ['natt-branch uten review-label', { labels: [] }],
    ['natt-branch med annen label', { labels: ['needs-manual-qa'] }],
    ['review-label uten natt-branch', { headRef: 'claude/ci-vakt-1234' }],
  ])('%s → skip ikke-natt-pr', (_navn, over) => {
    expect(classifyNattDraft(pr(over), NOW)).toEqual({ action: 'skip', reason: 'ikke-natt-pr' });
  });

  // Regel 3 — fersk aktivitet betyr at økta kan være midt i arbeidet.
  it('fersk aktivitet → skip fersk-aktivitet', () => {
    expect(classifyNattDraft(pr({ updatedAt: FERSK }), NOW)).toEqual({
      action: 'skip',
      reason: 'fersk-aktivitet',
    });
  });

  it('nøyaktig 90 minutter stille er stille nok', () => {
    const grensen = new Date(NOW.getTime() - MIN_QUIET_MINUTES * 60_000).toISOString();
    expect(classifyNattDraft(pr({ updatedAt: grensen }), NOW)).toEqual({ action: 'flip' });
  });

  it('uleselig tidsstempel behandles som fersk (fail-closed)', () => {
    expect(classifyNattDraft(pr({ updatedAt: 'i går' }), NOW)).toEqual({
      action: 'skip',
      reason: 'fersk-aktivitet',
    });
  });

  // Regel 4 — markørkommentarene (nattkjoreren.md steg 0.3 + steg 5).
  it('ingen markørkommentar → skip (Steg 5 aldri nådd)', () => {
    expect(classifyNattDraft(pr({ commentBodies: [] }), NOW)).toEqual({
      action: 'skip',
      reason: 'ingen-leveransemarkør',
    });
  });

  it('kommentarer uten markør teller ikke som leveranse', () => {
    const bodies = ['Ser bra ut!', 'alternativ B', '_Generated by Claude Code_'];
    expect(classifyNattDraft(pr({ commentBodies: bodies }), NOW)).toEqual({
      action: 'skip',
      reason: 'ingen-leveransemarkør',
    });
  });

  it('siste markør er 🔁 → skip uferdig-ombygging', () => {
    const bodies = ['🤖 Leveranse: alternativ A', '🔁 Bygger om til alternativ B i natt'];
    expect(classifyNattDraft(pr({ commentBodies: bodies }), NOW)).toEqual({
      action: 'skip',
      reason: 'uferdig-ombygging',
    });
  });

  it('🔁 fulgt av en ny 🤖-leveranse → flip (ombyggingen ble levert)', () => {
    const bodies = [
      '🤖 Leveranse: alternativ A',
      '🔁 Bygger om til alternativ B i natt',
      '🤖 Leveranse: alternativ B — nå bygget',
    ];
    expect(classifyNattDraft(pr({ commentBodies: bodies }), NOW)).toEqual({ action: 'flip' });
  });

  // Rekkefølgen er kontrakt: en fersk, ikke-natt-PR skal rapporteres som
  // ikke-natt-pr — den er utenfor sweepens rekkevidde uansett hvor gammel den er.
  it('regelrekkefølgen: ikke-natt slår ut før fersk-aktivitet', () => {
    expect(classifyNattDraft(pr({ headRef: 'fiks-noe', updatedAt: FERSK }), NOW)).toEqual({
      action: 'skip',
      reason: 'ikke-natt-pr',
    });
  });

  it('regelrekkefølgen: ikke-åpen-draft slår ut før alt annet', () => {
    const utenfor = pr({ isDraft: false, headRef: 'fiks-noe', updatedAt: FERSK, commentBodies: [] });
    expect(classifyNattDraft(utenfor, NOW)).toEqual({ action: 'skip', reason: 'ikke-åpen-draft' });
  });
});

describe('preCommentSkipReason', () => {
  it('null når PR-en er kandidat — runneren henter kommentarene først da', () => {
    const { commentBodies: _ignorert, ...fakta } = pr();
    expect(preCommentSkipReason(fakta, NOW)).toBeNull();
  });

  it('gir samme grunn som classifyNattDraft for de kommentarløse portene', () => {
    const { commentBodies: _ignorert, ...fakta } = pr({ updatedAt: FERSK });
    expect(preCommentSkipReason(fakta, NOW)).toBe('fersk-aktivitet');
  });
});

describe('lastNattMarker', () => {
  it('leser markøren selv med ledende blanktegn', () => {
    expect(lastNattMarker(['\n  🤖 Leveranse'])).toBe(DELIVERY_MARKER);
    expect(lastNattMarker(['  🔁 Bygger om'])).toBe(REBUILD_MARKER);
  });

  it('markør midt i teksten teller ikke — kun kommentarens åpning', () => {
    expect(lastNattMarker(['Nattkjøreren bruker 🤖 som markør'])).toBeNull();
  });

  it('siste markørkommentar vinner', () => {
    expect(lastNattMarker(['🔁 om', 'prat', '🤖 levert', 'mer prat'])).toBe(DELIVERY_MARKER);
  });
});

// Låser de to egenskapene 🧹-prefikset ble valgt for (#1769). Drifter teksten,
// begynner sweepens egen kommentar å bli lest enten som nattkjørerens leveranse
// eller som et eier-svar — begge deler ville forgiftet natt-loopen.
describe('audit-kommentaren', () => {
  it('starter med 🧹 og er ikke en 🤖/🔁-markørkommentar', () => {
    const body = buildSweepComment();
    expect(body.startsWith(SWEEP_MARKER)).toBe(true);
    expect(SWEEP_MARKER).not.toBe(DELIVERY_MARKER);
    expect(SWEEP_MARKER).not.toBe(REBUILD_MARKER);
    // Selve filteret nattkjøreren bruker (steg 0.3) — ikke en håndskrevet kopi.
    expect(lastNattMarker([body])).toBeNull();
    // Hele teksten, ikke bare åpningen: en fremtidig `includes`-lesning av
    // markørene må heller ikke kunne treffe midt i setningen.
    expect(body).not.toMatch(/🤖|🔁/);
  });

  it('matcher ikke eier-svar-regexen fra nattkjøreren steg 0.3', () => {
    const body = buildSweepComment();
    expect(/^\s*alternativ\s*(B|C)\b/i.test(body)).toBe(false);
    // Belte og seler: heller ikke linjevis, om mønsteret en dag leses med /m.
    expect(/^\s*alternativ\s*(B|C)\b/im.test(body)).toBe(false);
  });

  it('nevner #1769 så en leser finner opphavet', () => {
    expect(buildSweepComment()).toContain('#1769');
  });
});

// LOCKSTEP mot workflow-fila: konstantene og runneren er verdiløse hvis
// workflowen ikke kaller dem. Drifter navnet eller tokenet, feiler denne testen
// i stedet for at sweepen stille slutter å kjøre.
describe('lockstep mot .github/workflows/natt-draft-sweep.yml', () => {
  const workflow = fs.readFileSync(
    path.resolve(__dirname, '../../.github/workflows/natt-draft-sweep.yml'),
    'utf-8',
  );

  it('kjører scripts/loops/sweep-natt-drafts.ts', () => {
    expect(workflow).toContain('scripts/loops/sweep-natt-drafts.ts');
  });

  it('bruker PR_AUTHOR_PAT — github.token ville aldri trigget kortet (#1701)', () => {
    expect(workflow).toContain('secrets.PR_AUTHOR_PAT');
  });

  it('cron-uttrykket står — et stille droppet schedule er et nett ingen savner', () => {
    expect(workflow).toContain("'30 5 * * *'");
  });
});

describe('konstantene', () => {
  it('speiler natt-PR-signaturen', () => {
    expect(NATT_BRANCH_PREFIX).toBe('claude/natt-');
    expect(NATT_REVIEW_LABEL).toBe('autonomy:review');
    expect(MIN_QUIET_MINUTES).toBe(90);
  });
});
